---
runtime: custom
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1.4
  disk_size_gb: 10

env_variables:
  POKER_APP_ENV: production
  REACT_CLIENT_BUILD_DIR: /usr/local/lib/poker-app/client
